version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    command: --smallfiles --rest
  redis:
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
  # nginx+passenger
  # there's a rails app and a node app
  webapp:
    restart: always
    build: ./
    volumes:
      - ./server:/home/app/ruby-api         # rails app
      - ./api:/home/app/node-api            # node app
      - ./data/:/data                       # project data dir
      - assets:/home/app/server/public      # front end assets
      - gtfs_sources:/data/gtfs_sources     # GTFS input data
      - bundle:/bundle                      # for bundle installs
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
      - mongodb
      - elasticsearch
    environment: &app_environment
      # PostgreSQL Development Database:
      DATABASE_URL: postgres://postgres:omg_development@db:5432/omg_development?pool=5&encoding=unicode&schema_search_path=public
      REDIS_URL: redis://redis:6379/0
      # Enable the byebug debugging server - this can be overriden
      # from the command line:
      ENABLE_DEBUG_SERVER: 'true'

      # Run Rails in dev mode
      RACK_ENV: development
      RAILS_ENV: development

      # Rails secrets
      secret_key: 'not really a secret key for now kasjdbfjasdhblajb vlak34qaw4ar'
      secret_token: 'not really a secret token for now kasjdbfjasdhblajb vlak34qaw4ar'
      google_maps_api_key: idk
      sendgrid_user: omg_transit
      sendgrid_password: idk
#  nodeweb:
#    command: npm start
#    build:
#      context: ./api
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./api:/usr/src/api
#      - ./data:/usr/src/data
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
#      - mongodb
volumes:
  bundle:       # cached bundler stuff
  mongodata:    # mongodb data
  assets:       # web site assets go here
  gtfs_sources: # GTFS data gets downloaded here when imported
