version: '2'
services:
  mongodb:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    command: --smallfiles --rest
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:5.4-alpine
    ports:
      - "9200:9200"
      - "9300:9300"
  db:
    image: mdillon/postgis:9.6-alpine
    ports:
      - "5432:5432"
  builder:
    restart: always
    build: ./frontend
    command: /bin/sh -c "npm install && grunt dev" # grunt doesn't honor NODE_PATH
    volumes:
      - .:/application
  webapp:
    restart: always
    build: .
    command: /sbin/my_init --enable-insecure-key
    volumes:
      - ./server:/home/app/ruby-api                    # rails app
      - ./api:/home/app/node-api                       # node app
      - ./data/:/home/app/data                         # project data dir
      - ./frontend/www:/home/app/rails-api/public      # front end assets
      - gtfs_sources:/data/gtfs_sources                # GTFS input data
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
      - mongodb
      - elasticsearch
    environment: &app_environment
      # PostgreSQL Development Database:
      DATABASE_URL: postgres://postgres:omg_development@db:5432/omg_development?pool=5&encoding=unicode&schema_search_path=public
      REDIS_URL: redis://redis:6379/0
      MONGO_HOST: "mongodb://mongodb:27017/"
      REDIS_HOST: "redis"
      # Enable the byebug debugging server - this can be overriden
      # from the command line:
      ENABLE_DEBUG_SERVER: 'true'

      # Run Rails in dev mode
      RACK_ENV: development
      RAILS_ENV: development
      RAILS_SECRET_TOKEN: "some secret phrase of at least 30 characters sdfkndflgjbasfkgjbsdfkjgbsdfg"

      # Rails secrets
      DEVISE_SECRET_KEY: 'not really a secret key for now kasjdbfjasdhblajb vlak34qaw4ar'
      GOOGLE_MAPS_API_KEY: idk
      SENDGRID_USER: omg_transit
      SENDGRID_PASSWORD: idk
volumes:
  mongodata:    # mongodb data
  gtfs_sources: # GTFS data gets downloaded here when imported
